### PR TITLE
Handle null after space increase

### PR DESCRIPTION
**Pull request by msvinaykumar**
Merging from RM to MVP

https://github.com/kruize/autotune/pull/1077
https://github.com/kruize/autotune/pull/1071

### CODE REVIEW

**Comment by dinogun** [comment]
@msvinaykumar can you please indicate how this has been tested, thanks

**Comment by msvinaykumar** [comment]
> @msvinaykumar can you please indicate how this has been tested, thanks

this issue not able to reproduce locally as it requires DB size increase to existing DB without clean up command.
The potential issue is that after an increase in database size, the DataSource column, which is of type JSONB, is not being set to its default value. However, it allows for this if we perform a database cleanup. Therefore, the solution is to set the default value of the JSONB-type column to null.

Normal testcases should pass.

**Comment by dinogun** [comment]
@chandrams can you review this

**Comment by chandrams** [comment]
@dinogun - I have tested this PR with the kruize release 0.0.19.5 with 30 exps / 15 days and updated Recommendations, with the same postgres DB restarted only kruize with the build containing this PR 1085, posted a day's results for the same 30 exps and invoked updateRecommendations. Uploading results and recommendations generation worked as expected.

**Review by chandrams — APPROVED** [review]
LGTM

**Pull request merged**
