### PR TITLE
Shutsdown kubernetes client after it's usage

### PR DESCRIPTION
**Pull request by bharathappali**
This PR adds a trivial change to shutdown the kubernetes client after it's usage

Signed-off-by: bharathappali <abharath@redhat.com>

### CODE REVIEW

**Comment by bharathappali** [comment]
Fixes #524

**Comment by dinogun** [comment]
@bharathappali is this PR still required?

**Comment by bharathappali** [comment]
@dinogun `AutotuneDeployment.java` was deleted and `KruizeDeployment.java` takes care of the workflow, Made changes in the `KruizeDeployment.java` now to make sure the `kubernetes client` is closed after it's usage

**Comment by dinogun** [comment]
Closing redundant PRs

**Pull request closed without merging**
