### PR TITLE
updateRecommendation API.

### PR DESCRIPTION
**Pull request by msvinaykumar**

### CODE REVIEW

**Comment by dinogun** [comment]
@msvinaykumar have you tested if the recommendation changes when old result data is added after a recommendation is produced

**Comment by msvinaykumar** [comment]
> @msvinaykumar have you tested if the recommendation changes when old result data is added after a recommendation is produced

Yes

**Comment by dinogun** [comment]
@msvinaykumar there seems to be a build failure, can you PTAL
```
Error: ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project autotune: Compilation failure
Error: ERROR] /home/autotune/src/autotune/src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java:[28,8] com.autotune.database.dao.ExperimentDAOImpl is not abstract and does not override abstract method isDataExistsInResults(java.lang.String,java.sql.Timestamp) in com.autotune.database.dao.ExperimentDAO
```

**Comment by msvinaykumar** [comment]
> @msvinaykumar there seems to be a build failure, can you PTAL
> 
> ```
> Error: ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project autotune: Compilation failure
> Error: ERROR] /home/autotune/src/autotune/src/main/java/com/autotune/database/dao/ExperimentDAOImpl.java:[28,8] com.autotune.database.dao.ExperimentDAOImpl is not abstract and does not override abstract method isDataExistsInResults(java.lang.String,java.sql.Timestamp) in com.autotune.database.dao.ExperimentDAO
> ```

fixed

**Review by dinogun — APPROVED** [review]
LGTM

**Comment by dinogun** [comment]
build_crc PR job is expected to fail until #836 gets merged

**Pull request merged**
