### PR TITLE
Adding tests to validate autotune object id

### PR DESCRIPTION
**Pull request by shruacha1234**
Signed-off-by: Shruthi <Shruthi.Acharya@ibm.com>

### CODE REVIEW

**Comment by chandrams** [comment]
@shruacha1234 - can you please resolve the conflicts.

**Review by chandrams — APPROVED** [review]

**Review by dinogun — COMMENTED** [review]
Why is there an empty file `tests/scripts/modify_autotune_config_tests.sh`

**Comment by shruacha1234** [comment]
> Why is there an empty file `tests/scripts/modify_autotune_config_tests.sh`

Have added execute permission to  `tests/scripts/modify_autotune_config_tests.sh`

**Review by dinogun — APPROVED** [review]
Great set of tests !

**Pull request merged**
