### PR TITLE
Updated scripts and workflows to test kruize docker image from the manifest yaml

### PR DESCRIPTION
**Pull request by chandrams**
Updated scripts and workflows to test kruize docker image from the manifest yaml

### CODE REVIEW

**Comment by chandrams** [comment]
run functional tests

**Comment by dinogun** [comment]
@chandrams Please fix the conflicts

**Comment by dinogun** [comment]
@chandrams Please fix the conflicts

**Comment by chandrams** [comment]
@dinogun I have resolved the conflicts, please review.

**Comment by dinogun** [comment]
So is the test_crc_manifest_build job expected to fail?

**Comment by chandrams** [comment]
From the Logs I see it is still using 0.0.19.4_rm build, let me push a change and trigger the build again

```
 Normal  Pulling    108s  kubelet            Pulling image "kruize/autotune_operator:0.0.19.4_rm"
 Normal  Pulled     102s  kubelet            Successfully pulled image "kruize/autotune_operator:0.0.19.4_rm" in 6.383105776s
```

**Comment by chandrams** [comment]
Now it picked the build from the manifest which is 0.0.20_rm but failed as the build is not available on docker.hub

```
 Normal   Pulling    12m (x4 over 14m)     kubelet            Pulling image "kruize/autotune_operator:0.0.20_rm"
  Warning  Failed     12m (x4 over 14m)     kubelet            Failed to pull image "kruize/autotune_operator:0.0.20_rm": rpc error: code = Unknown desc = Error response from daemon: manifest for kruize/autotune_operator:0.0.20_rm not found: manifest unknown: manifest unknown
```

**Review by dinogun — APPROVED** [review]
Merging as the manifest job is expected fail during a release

**Pull request merged**
