### PR TITLE
Fixed Issue_362: Autotune Query URL update

### PR DESCRIPTION
**Pull request by khansaad**
Signed-off-by: Saad Khan <saakhan@redhat.com>

### CODE REVIEW

**Comment by dinogun** [comment]
@khansaad Can you please paste how the output of `listApplicationTunables` looks like now with this change?

**Comment by chandrams** [comment]
@khansaad - As discussed, please verify output of both listStackTunables and listAutotuneTunables API and check if the fix is seen across all references.

**Comment by khansaad** [comment]
> @khansaad Can you please paste how the output of `listApplicationTunables` looks like now with this change?

Here it is:


Screenshot from 2022-01-25 13-27-31

**Comment by khansaad** [comment]
> 
Screenshot from 2022-01-25 13-30-29

@chandrams Yes, It's getting reflected in both the APIs

**Review by dinogun — APPROVED** [review]
LGTM

**Review by chandrams — APPROVED** [review]
This requires test changes I think we can do it in another PR. Changes look good to me.

**Pull request merged**
