### PR TITLE
Adds changes to RecommendationItem enum to accomodate MIG strings

### LINKED ISSUE #1312: GPU MIG Right sizing recommendations by kruize
### Describe the feature 

Kruize reads CPU & memory usage data from the provided data source and comes up with the CPU and Memory right sizing recommendation. In a similar way it would be good to have the GPU MIG partition sizing recommendation for container which utilise GPU's

### Examples or references

Most of the ML workloads need GPU power and advanced GPU's from NVIDIA support MIG (Multi instance GPU's) where a single Physical GPU can be partitioned into multi instances of virtual or logical GPU's which can be configured and shared across multiple containers. Ampere (from A30) and Hopper series GPU's provide this feature.

### Suggest a solution

- Record the GPU related metrics
- Process the metrics along with CPU and Memory metrics
- Provide MIG partition recommendation

### Additional Context

None

### PR DESCRIPTION
**Pull request by bharathappali**
## Description

This PR is fourth part of the set of PR's which will be raised for adding GPU support #1312

This PR adds changes to RecommendationItem enum to accomodate MIG strings

This PR is build on top of #1317, so it needs to be merged after merging #1317

Fixes #1312 

### Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Docs update
- [ ] Breaking change (What changes might users need to make in their application due to this PR?)
- [ ] Requires DB changes

## How has this been tested?

Tests will be added in the subsequent PR

- [ ] New Test X
- [ ] Functional testsuite

**Test Configuration**
* Kubernetes clusters tested on: 

## Checklist :dart:

- [ ] Followed coding guidelines
- [ ] Comments added
- [ ] Dependent changes merged
- [ ] Documentation updated
- [ ] Tests added or updated

## Additional information

None

### CODE REVIEW

**Comment by dinogun** [comment]
@bharathappali Needs to be rebased against mvp_demo

**Comment by bharathappali** [comment]
Apologies for the overlook, I have rebased to `mvp_demo`. Thanks @dinogun

**Comment by dinogun** [comment]
@bharathappali Please rebase as I've merged your earlier PRs

**Comment by dinogun** [comment]
@bharathappali The crc PR check is failing. Looks like some tests need to be updated with the new CONSTANTS

**Comment by bharathappali** [comment]
@dinogun Yes we need the adapter for the recommendation item enum, as the changes are getting lengthy I have added them in subsequent PR's

**Comment by bharathappali** [comment]
@dinogun As there is no adapter the keys in recommendation are changed in this way

```
"variation": {
                            "requests": {
                              "MEMORY": {
                                "amount": 187.98999999999998,
                                "format": "MiB"
                              },
                              "CPU": {
                                "amount": -0.17000000000000015,
                                "format": "cores"
                              }
                            },
                            "limits": {
                              "MEMORY": {
                                "amount": 138.2,
                                "format": "MiB"
                              },
                              "CPU": {
                                "amount": 0.42999999999999994,
                                "format": "cores"
                              }
                            }
                          },
```

This will be fixed in #1321

**Comment by dinogun** [comment]
Merging with the assumption that  PR #1321 will fix the test failures

**Pull request merged**
