### PR TITLE
Fault tolerant test for kruize local

### PR DESCRIPTION
**Pull request by chandrams**
Included a test to validate list experiments, list recommendations, list datasources, list metadata after kruize restart

### CODE REVIEW

**Review by khansaad — COMMENTED** [review]
@chandrams This seems to be working fine except at the end we're seeing test failure message.
```
Test took 403 seconds to complete
Local Monitoring Fault tolerant test failed! Check the logs for details
```
On checking the logs, found out that it's because of the error message coming while deploying autotune:
```
...
2024-09-0309:32:23.675 INFO [main][DataSourceCollection.java(53)]-Datasource found: prometheus-1
2024-09-0309:32:23.732 ERROR [main][DataSourceCollection.java(146)]-Datasource: prometheus-1 already exists!
...
```
I think we can change this to warning later on.

Also, all PR checks are failing due to this reason:
```

create performance profile status = 
Failed! Create performance profile failed. Status - 
########################################################################

Error: Process completed with exit code 1.
```

**Comment by chandrams** [comment]
@khansaad - I did a rebase on mvp demo & restarted the PR checks, they pass now.

**Review by khansaad — APPROVED** [review]
LGTM!

**Review by msvinaykumar — APPROVED** [review]
LGTM

**Pull request merged**
