### PR TITLE
Documentation Update for Supported Metric Types in updateResults

### PR DESCRIPTION
**Pull request by shekhar316**
This PR solves the issue https://github.com/kruize/autotune/issues/1048

- The updated supported units (https://github.com/kruize/autotune/pull/1038) for CPU and Memory Usages are documented.

### CODE REVIEW

**Review by khansaad — APPROVED** [review]
LGTM

**Review by dinogun — APPROVED** [review]
LGTM

**Comment by dinogun** [comment]
@shekhar316 Can you please fix the conflicts

**Comment by shekhar316** [comment]
@dinogun Sure, I've resolved the conflicts. Thanks

**Pull request merged**
