### PR TITLE
Fix updateResults duration check

### PR DESCRIPTION
**Pull request by dinogun**

### CODE REVIEW

**Comment by dinogun** [comment]
@chandrams This should fix the duration check for updateResults in tests. Please check

**Comment by chandrams** [comment]
@dinogun - Thanks for the fix. Tested it, a small update is required to the below message, 5 seconds needs to 30 seconds.

"In the message "Interval duration cannot be less than or greater than measurement_duration by more than 5 seconds"

**Comment by dinogun** [comment]
@chandrams sorry yeah I missed that, added it now

**Review by chandrams — APPROVED** [review]
LGTM

**Pull request merged**
