### PR TITLE
Add support for Kubernetes workload type - 'job'

### PR DESCRIPTION
**Pull request by khansaad**
## Description

Add a new feature to support the `job` workload type along with `deployments`

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Docs update
- [ ] Breaking change (What changes might users need to make in their application due to this PR?)
- [ ] Requires DB changes

## How has this been tested?

Please describe the tests that were run to verify your changes and steps to reproduce. Please specify any test configuration required. 

- [ ] New Test X
- [ ] Functional testsuite

**Test Configuration**
* Kubernetes clusters tested on: Minikube, Openshift

## Checklist :dart:

- [ ] Followed coding guidelines
- [ ] Comments added
- [ ] Dependent changes merged
- [ ] Documentation updated
- [ ] Tests added or updated

## Additional information

Include any additional information such as links, test results, screenshots here

### CODE REVIEW

**Review by msvinaykumar — APPROVED** [review]
LGTM

**Comment by chandrams** [comment]
@khansaad - You will need to add tests to include job type.  Also update the list of supported kubernetes types in the existing tests to include job type.

**Comment by khansaad** [comment]
> @khansaad - You will need to add tests to include job type. Also update the list of supported kubernetes types in the existing tests to include job type.

Added the same now. Running the PR test on jenkins:
https://ci.app-svc-perf.corp.redhat.com/job/ExternalTeams/job/Autotune/job/kruize_test_pull_request/107/

**Comment by khansaad** [comment]
@chandrams I think the test failures I'm seeing are the existing ones only and not related to the changes I made. Attaching the jenkins logs, please confirm once.
[kruize_functional_test_results_pr-1223.zip](https://github.com/user-attachments/files/16832814/kruize_functional_test_results_pr-1223.zip)

**Comment by chandrams** [comment]
Yes, failures are existing ones.

In the list recommendations test for job output, list recommendations says not enough data thought update recommendations has short term recommendations

```
Listing the recommendations...
URL =  http://10.88.0.20:31455/listRecommendations
PARAMS =  {'experiment_name': 'quarkus-resteasy-kruize-min-http-response-time-db'}
Response status code =  200

************************************************************
[
  {
    "cluster_name": "cluster-one-division-bell",
    "kubernetes_objects": [
      {
        "type": "job",
        "name": "tfb-qrh-job",
        "namespace": "default",
        "containers": [
          {
            "container_image_name": "kruize/tfb-qrh:1.13.2.F_et17",
            "container_name": "tfb-server-1",
            "recommendations": {
              "version": "1.0",
              "notifications": {
                "120001": {
                  "type": "info",
                  "message": "There is not enough data available to generate a recommendation.",
                  "code": 120001
                }
              },
              "data": {}
            }
          },
          {
            "container_image_name": "kruize/tfb-db:1.15",
            "container_name": "tfb-server-0",
            "recommendations": {
              "version": "1.0",
              "notifications": {
                "120001": {
                  "type": "info",
                  "message": "There is not enough data available to generate a recommendation.",
                  "code": 120001
                }
              },
              "data": {}
            }
          }
        ]
      }
    ],
    "version": "v2.0",
    "experiment_name": "quarkus-resteasy-kruize-min-http-response-time-db"
  }
]
```
Can you check this.

**Comment by khansaad** [comment]
> Yes, failures are existing ones.
> 
> In the list recommendations test for job output, list recommendations says not enough data thought update recommendations has short term recommendations
> 
> ```
> Listing the recommendations...
> URL =  http://10.88.0.20:31455/listRecommendations
> PARAMS =  {'experiment_name': 'quarkus-resteasy-kruize-min-http-response-time-db'}
> Response status code =  200
> 
> ************************************************************
> [
>   {
>     "cluster_name": "cluster-one-division-bell",
>     "kubernetes_objects": [
>       {
>         "type": "job",
>         "name": "tfb-qrh-job",
>         "namespace": "default",
>         "containers": [
>           {
>             "container_image_name": "kruize/tfb-qrh:1.13.2.F_et17",
>             "container_name": "tfb-server-1",
>             "recommendations": {
>               "version": "1.0",
>               "notifications": {
>                 "120001": {
>                   "type": "info",
>                   "message": "There is not enough data available to generate a recommendation.",
>                   "code": 120001
>                 }
>               },
>               "data": {}
>             }
>           },
>           {
>             "container_image_name": "kruize/tfb-db:1.15",
>             "container_name": "tfb-server-0",
>             "recommendations": {
>               "version": "1.0",
>               "notifications": {
>                 "120001": {
>                   "type": "info",
>                   "message": "There is not enough data available to generate a recommendation.",
>                   "code": 120001
>                 }
>               },
>               "data": {}
>             }
>           }
>         ]
>       }
>     ],
>     "version": "v2.0",
>     "experiment_name": "quarkus-resteasy-kruize-min-http-response-time-db"
>   }
> ]
> ```
> 
> Can you check this.

Updated now

**Comment by chandrams** [comment]
@khansaad - Can you rerun the sanity test & check if it works

**Comment by khansaad** [comment]
> @khansaad - Can you rerun the sanity test & check if it works
[sanity.zip](https://github.com/user-attachments/files/16835550/sanity.zip)

Re-ran the sanity and able to see it the correct results now

**Comment by khansaad** [comment]
[assets.zip](https://github.com/user-attachments/files/16835802/assets.zip)
attached css file

**Review by chandrams — APPROVED** [review]
LGTM

**Pull request merged**
