### PR TITLE
Added Property placeholders for gson and fixed missing properties pla…

### PR DESCRIPTION
**Pull request by oscerd**
…ceholders usage

Minimal changes for correct usage of properties placeholder

### CODE REVIEW

**Review by dinogun — APPROVED** [review]
LGTM!

**Comment by dinogun** [comment]
@oscerd Thank you for submitting the PR! Please note that we require all submitters to use their GPG keys to sign the commits so that we can verify the submitters. Please see [contributing](https://github.com/kruize/autotune/blob/master/CONTRIBUTING.md) and resubmit with the signed commit. Thanks!

**Comment by oscerd** [comment]
Should be fine now.

**Comment by dinogun** [comment]
> Should be fine now.

Maybe you need to do a force push, don't see the commit as verified yet.

**Pull request closed without merging**
