### PR TITLE
Update List Exp API with new query params

### LINKED ISSUE #722: listExperiments API JSON updates
As with `listRecommendations`, `listExperiments` should default to being less verbose.

1. Default should not print either `recommendations` or `results`.
2. Add three new query params `results`, `recommendations` and `latest`.
3. `/listExperiments?results=true` should print the latest result and no recommendations.
4. `/listExperiments?results=true&latest=false` should print all results and no recommendations.
5. `/listExperiments?recommendations=true` should print the latest recommendation and no results.
6. `/listExperiments?recommendations=true&latest=false` should print all recommendations and no results.
7. `/listExperiments?results=true&recommendations=true&latest=false` should print everything.

### PR DESCRIPTION
**Pull request by khansaad**
This PR fixes #722

### CODE REVIEW

**Comment by chandrams** [comment]
@khansaad - Please include a design doc for listExperiments with all the supported input parameters (results, recommendations, latest, experiment_name). Include functional tests to test the below with single and multiple experiments.

- /listExperiments without any parameters
  - validate only experiment details are displayed and they match with the created experiments
  - validate none of the results or recommendations are displayed
- /listExperiments?results=true 
   - validate latest results are displayed without recommendations and results are as expected
   - Post multiple results and validate latest result is shown for the experiments
- /listExperiments?results=true&latest=false 
   - validate all the results are displayed without recommendations
- /listExperiments?recommendations=true
  - validate only if the latest recommendation is displayed without any results
- /listExperiments?recommendations=true&latest=false 
   - validate if all recommendations are displayed for all the experiments and without results.
- /listExperiments?results=true&recommendations=true&latest=false
  - validate if all the results and recommendations are displayed for all the experiments

The above tests need to be included with experiment_name parameter & without experiment_name (are we supporting this?)

Negative cases:
- Check the response codes and error messages with invalid values for the input parameters:
  - If experiment_name is supported check the behavior with a non-existing experiment_name
  - Invalid values for results, recommendations
- Delete a few experiments and ensure it is not listed as part of listExperiments, what is the behavior if we query with results or recommendations to true and latest = false?
- Create experiments, without update results 
    - validate no results are displayed when results=true and results=true&latest=false
    - validate no recommendations are displayed with recommendations=true and recommendations=true&latest=false
    - validate listExperiments without any parameters
    - updateResults for a few exps and validate if results / recommendations are shown only for those

**Comment by khansaad** [comment]
> @khansaad - Please include a design doc for listExperiments with all the supported input parameters (results, recommendations, latest, experiment_name). Include functional tests to test the below with single and multiple experiments.
> 
> * /listExperiments without any parameters
>   
>   * validate only experiment details are displayed and they match with the created experiments
>   * validate none of the results or recommendations are displayed
> * /listExperiments?results=true
>   
>   * validate latest results are displayed without recommendations and results are as expected
>   * Post multiple results and validate latest result is shown for the experiments
> * /listExperiments?results=true&latest=false
>   
>   * validate all the results are displayed without recommendations
> * /listExperiments?recommendations=true
>   
>   * validate only if the latest recommendation is displayed without any results
> * /listExperiments?recommendations=true&latest=false
>   
>   * validate if all recommendations are displayed for all the experiments and without results.
> * /listExperiments?results=true&recommendations=true&latest=false
>   
>   * validate if all the results and recommendations are displayed for all the experiments
> 
> The above tests need to be included with experiment_name parameter & without experiment_name (are we supporting this?)
> 
> Negative cases:
> 
> * Check the response codes and error messages with invalid values for the input parameters:
>   
>   * If experiment_name is supported check the behavior with a non-existing experiment_name
>   * Invalid values for results, recommendations
> * Delete a few experiments and ensure it is not listed as part of listExperiments, what is the behavior if we query with results or recommendations to true and latest = false?
> * Create experiments, without update results
>   
>   * validate no results are displayed when results=true and results=true&latest=false
>   * validate no recommendations are displayed with recommendations=true and recommendations=true&latest=false
>   * validate listExperiments without any parameters
>   * updateResults for a few exps and validate if results / recommendations are shown only for those

Updated the MointoringAPI doc to include the new listExperiments changes. 
Working on the test changes in a separate PR.

**Comment by dinogun** [comment]
@khansaad Still seeing one issue with the latest changes 
`/listExperiments?experiment_name=quarkus-resteasy-kruize-min-http-response-time-db_0&recommendations=true`
This should provide only the latest recommendation for the given experiment and not all. I am seeing all of the recommendations. (default should be `latest=false`)

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
