### PR TITLE
Undoing the rolling update to get back to the old config

### PR DESCRIPTION
**Pull request by bharathappali**
This change will revert back to the old config of the deployment

Signed-off-by: bharathappali <abharath@redhat.com>

### CODE REVIEW

**Comment by bharathappali** [comment]
Using deep copy of the deployment object to save in ETD and use back in clean up

**Comment by bharathappali** [comment]
will fix #413

**Comment by bharathappali** [comment]
Changed the field `currentDeployment` to `defaultDeployment` along with respective `getter` and `setter` functions, to be more clear about it's usage and avoid confusion about the objective of the particular field.

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
