### PR TITLE
Included the scalability test for kruize

### PR DESCRIPTION
**Pull request by chandrams**
Included the scalability test for kruize

### CODE REVIEW

**Comment by dinogun** [comment]
@chandrams why is the PR check failing here

**Comment by chandrams** [comment]
@dinogun PR check failed due to maven issue. I have pulled the latest changes into my branch, it is passing now.

**Comment by dinogun** [comment]
This is based on #796, merging this and closing #796

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
