### PR TITLE
Included stress test into the release test workflow

### PR DESCRIPTION
**Pull request by chandrams**

### CODE REVIEW

**Comment by chandrams** [comment]
@dinogun - It took 1 hr 2 mins for stress test and total execution time was 1 hr 14 mins - [link to the run](https://github.com/chandrams/demo/actions/runs/6479821632)

**Comment by dinogun** [comment]
@chandrams so without the stress test, earlier release testing used to finish in 12 mins?

**Comment by chandrams** [comment]
@dinogun - Yes, since stress test runs on github hosted runners which are of low config it takes time. Regular release testing however is done on Jenkins and good config machines so there it takes lesser time.

**Comment by chandrams** [comment]
@dinogun - Can you please review this, thank you.

**Pull request merged**
