### PR TITLE
Adds GPU queries to performance profile

### PR DESCRIPTION
**Pull request by bharathappali**
## Description

This PR is a first's part of the set of PR's which will be raised for adding GPU support #1312 

This PR adds the GPU queries to the performance profile YAML

Fixes # (issue)

### Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Docs update
- [ ] Breaking change (What changes might users need to make in their application due to this PR?)
- [ ] Requires DB changes

## How has this been tested?

Test coverage will be done in a separate PR

- [ ] New Test X
- [ ] Functional testsuite

**Test Configuration**
* Kubernetes clusters tested on: 

## Checklist :dart:

- [x] Followed coding guidelines
- [x] Comments added
- [ ] Dependent changes merged
- [ ] Documentation updated
- [ ] Tests added or updated

## Additional information
None

### CODE REVIEW

**Comment by bharathappali** [comment]
@msvinaykumar @dinogun The namespace code is not changed I have just make an alignment change, Please view in the complete file view and let me know if any changes are needed.

**Comment by dinogun** [comment]
@bharathappali Please update the JSON [file](https://github.com/kruize/autotune/blob/master/manifests/autotune/performance-profiles/resource_optimization_local_monitoring.json) as well for this. Also the non-recording rules versions of the [files](https://github.com/kruize/autotune/blob/master/manifests/autotune/performance-profiles/resource_optimization_local_monitoring_norecordingrules.yaml) need to be updated as well

**Comment by dinogun** [comment]
@kusumachalasani can you please review this

**Comment by bharathappali** [comment]
Thanks for the review @dinogun Will make the necessary changes and update the PR

**Comment by bharathappali** [comment]
Added the changes your requested @dinogun . Please let me know if any other changes needed.

**Review by dinogun — APPROVED** [review]
LGTM

**Comment by dinogun** [comment]
I'll merging this since this is the base PR on top of which all other GPU PRs are built on. However still need @kusumachalasani to sign off on this after she is back next week

**Comment by kusumachalasani** [comment]
As the current GPU queries doesn't differentiate the GPU Usage for the same container name in two different workloads (job, deployment) in a namespace - it would be worth gathering the metrics at pod level and group them with workload queries to aggregate the actual usage. Similar to what we planned for container level local monitoring queries.

**Comment by bharathappali** [comment]
@kusumachalasani Thanks for the review. Will make those changes and get back to you.

**Pull request merged**
