### PR TITLE
Bump remote monitoring image to 0.0.10_rm

### PR DESCRIPTION
**Pull request by dinogun**

### CODE REVIEW

**Comment by dinogun** [comment]
@chandrams Please approve this PR after tests are successful. Please attach test log for reference.

**Comment by chandrams** [comment]
Attaching the test results with kruize/autotune_operator:0.0.10_mvp build

[kruize-test-results-0.0.10-mvp.zip](https://github.com/kruize/autotune/files/10941858/kruize-test-results-0.0.10-mvp.zip)

**Comment by chandrams** [comment]
@dinogun - I have attached the results of all the tests we have in the repo as I 'm yet to create the release specific test list, so there are failures (related to both code and test) but haven't seen any new issues due to the initial DB changes.

**Review by chandrams — APPROVED** [review]
LGTM

**Pull request merged**
