### PR TITLE
Updated Analyzer API tests due to analyzer code changes

### PR DESCRIPTION
**Pull request by chandrams**
Updated Analyzer API tests due to analyzer code changes for experiment name, tunables and to use autotune yamls from benchmarks.

### CODE REVIEW

**Comment by chandrams** [comment]
Search Space API changes will be done in a separate PR

**Comment by dinogun** [comment]
@chandrams Since tests use the `jq` command extensively, can we add a check to see if `jq` is installed in the system where it is being run and if not error out gracefully.

**Comment by dinogun** [comment]
nm, Sorry I missed it in the `common_functions.sh`

**Review by dinogun — APPROVED** [review]
LGTM

**Comment by dinogun** [comment]
@chandrams Looks like some of the commits are not signed. Please make sure to sign them during commit. But will merge for now anyway.

**Pull request merged**
