### PR TITLE
Updating the app autotune yaml tests

### PR DESCRIPTION
**Pull request by shruacha1234**
Signed-off-by: Shruthi <Shruthi.Acharya@ibm.com>

### CODE REVIEW

**Review by dinogun — APPROVED** [review]
lgtm. @chandrams Can you please review as well. Thanks

**Comment by chandrams** [comment]
@shruacha1234 - deploy_autotune - there needs to be an error check here to check if autotune setup was successful. If autotune setup fails it shouldn't run the test. Is this implemented?

**Comment by shruacha1234** [comment]
> @shruacha1234 - deploy_autotune - there needs to be an error check here to check if autotune setup was successful. If autotune setup fails it shouldn't run the test. Is this implemented?

Have included in the other PR which I'll be raising soon

**Review by chandrams — APPROVED** [review]
lgtm

**Pull request merged**
